//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCTask.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblemployee_details
    {
        public int employee_id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public Nullable<System.DateTime> birth_date { get; set; }
        public string email_Address { get; set; }
        public string password { get; set; }
    }
}
